apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adminService.name }}
  labels:
    {{- include "apollo.labels" . | nindent 4 }}
    app.kubernetes.io/component: adminservice
spec:
  type: {{ .Values.adminService.service.type }}
  ports:
    - name: http
      port: {{ .Values.adminService.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "apollo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: adminservice
