{{- if .Values.database.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secret.name }}
  labels:
    {{- include "apollo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.secret.configPasswordKey }}: {{ .Values.database.secret.configPassword | quote }}
  {{ .Values.database.secret.portalPasswordKey }}: {{ .Values.database.secret.portalPassword | quote }}
{{- end }}
