replicaCount: 1

image:
  repository: 209479308066.dkr.ecr.us-east-1.amazonaws.com/ziyuanqishuo-frontend
  tag: frontend-5016c1a
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

kong:
  ingress:
    enabled: true
    className: kong
    path: /hanzi/app
    pathType: Prefix

probes:
  path: /healthz
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 3
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  fsGroup: 101

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
