replicaCount: 1

image:
  repository: svhd/logto
  tag: latest
  pullPolicy: IfNotPresent

logto:
  endpoint: http://localhost:3001
  adminEndpoint: http://localhost:3002
  trustProxyHeader: "1"
  secretName: logto-env

service:
  type: ClusterIP
  corePort: 3001
  adminPort: 3002

ingress:
  enabled: false
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  coreHost: logto.example.com
  adminHost: admin.logto.example.com

kong:
  ingress:
    enabled: false
    className: kong
    coreHost: logto.example.com
    adminHost: admin.logto.example.com

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

podSecurityContext: {}

securityContext: {}

nodeSelector: {}
tolerations: []
affinity: {}
