replicaCount: 1

image:
  repository: svhd/logto
  tag: latest
  pullPolicy: IfNotPresent

logto:
  endpoint: http://k8s-kong-kongalb-d47fba56e3-58647003.us-east-1.elb.amazonaws.com/logto
  adminEndpoint: http://k8s-kong-kongalb-d47fba56e3-58647003.us-east-1.elb.amazonaws.com/logto-admin
  trustProxyHeader: "1"
  secretName: logto-env

service:
  type: ClusterIP
  corePort: 3001
  adminPort: 3002

ingress:
  enabled: false
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  coreHost: logto.example.com
  adminHost: admin.logto.example.com

kong:
  ingress:
    enabled: true
    className: kong
    corePath: /logto
    adminPath: /logto-admin
    pathType: Prefix

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

podSecurityContext: {}

securityContext: {}

nodeSelector: {}
tolerations: []
affinity: {}
