apiVersion: v2
name: external-secrets-wrapper
description: GitOps wrapper for External Secrets Operator and AWS Secrets Manager ClusterSecretStore
type: application
version: 0.1.0
dependencies:
  - name: external-secrets
    version: 2.5.0
    repository: https://charts.external-secrets.io
