external-secrets:
  installCRDs: true

  serviceAccount:
    create: true
    name: external-secrets
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::209479308066:role/ai-video-platform-dev-external-secrets

clusterSecretStore:
  enabled: true
  name: aws-secrets-manager
  region: us-east-1
  serviceAccountName: external-secrets
  serviceAccountNamespace: external-secrets

appSecrets:
  enabled: true
  refreshInterval: 1h
  prefix: ai-video-platform/dev
