apiVersion: v2
name: dify-wrapper
description: GitOps wrapper for Dify on EKS
type: application
version: 0.1.0
dependencies:
  - name: dify
    version: 0.36.0
    repository: https://borispolonsky.github.io/dify-helm
