replicaCount: 2

image:
  repository: 209479308066.dkr.ecr.us-east-1.amazonaws.com/hello-springboot
  tag: main-initial
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/readiness
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

kong:
  ingress:
    enabled: true
    className: kong
    path: /hello
    pathType: Prefix
  rateLimit:
    enabled: true
    minute: 30
    policy: local

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  livenessPath: /actuator/health/liveness
  readinessPath: /actuator/health/readiness

serviceMonitor:
  enabled: true
  interval: 30s
  path: /actuator/prometheus
  labels:
    release: kube-prometheus-stack

nodeSelector: {}
tolerations: []
affinity: {}
