components:
  web:
    name: hello-web
    replicaCount: 2
    image:
      repository: 209479308066.dkr.ecr.us-east-1.amazonaws.com/hello-springboot
      tag: web-352cbf8
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 8080
    env:
      HELLO_GRPC_TARGET: hello-grpc.hello.svc.cluster.local:9090
      HELLO_DUBBO_URL: tri://hello-dubbo.hello.svc.cluster.local:50051
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  grpc:
    name: hello-grpc
    replicaCount: 1
    image:
      repository: 209479308066.dkr.ecr.us-east-1.amazonaws.com/hello-springboot
      tag: grpc-352cbf8
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      httpPort: 8081
      grpcPort: 9090
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  dubbo:
    name: hello-dubbo
    replicaCount: 1
    image:
      repository: 209479308066.dkr.ecr.us-east-1.amazonaws.com/hello-springboot
      tag: dubbo-352cbf8
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      httpPort: 8082
      dubboPort: 50051
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

ingress:
  enabled: false

kong:
  ingress:
    enabled: true
    className: kong
    path: /hello
    pathType: Prefix
  rateLimit:
    enabled: true
    minute: 30
    policy: local

probes:
  livenessPath: /actuator/health/liveness
  readinessPath: /actuator/health/readiness

serviceMonitor:
  enabled: true
  interval: 30s
  path: /actuator/prometheus
  labels:
    release: kube-prometheus-stack

nodeSelector: {}
tolerations: []
affinity: {}
