{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.secretName }}
  labels:
    app.kubernetes.io/name: flyte
    app.kubernetes.io/component: database-secret
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: db_password
{{- end }}
