apiVersion: v1
kind: Service
metadata:
  name: {{ include "logto.fullname" . }}
  labels:
    {{- include "logto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: core
      port: {{ .Values.service.corePort }}
      targetPort: core
      protocol: TCP
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "logto.selectorLabels" . | nindent 4 }}
