aws-load-balancer-controller:
  clusterName: ai-video-poc-dev
  region: us-east-1

  serviceAccount:
    create: true
    name: aws-load-balancer-controller
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::209479308066:role/ai-video-poc-dev-aws-load-balancer-controller

  replicaCount: 2
