{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.secretName }}
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_SERVICE_HOST
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: MYSQL_SERVICE_HOST
    - secretKey: MYSQL_SERVICE_PORT
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: MYSQL_SERVICE_PORT
    - secretKey: MYSQL_SERVICE_DB_NAME
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: MYSQL_SERVICE_DB_NAME
    - secretKey: MYSQL_SERVICE_USER
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: MYSQL_SERVICE_USER
    - secretKey: MYSQL_SERVICE_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: MYSQL_SERVICE_PASSWORD
    - secretKey: NACOS_AUTH_TOKEN
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: NACOS_AUTH_TOKEN
    - secretKey: NACOS_AUTH_IDENTITY_KEY
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: NACOS_AUTH_IDENTITY_KEY
    - secretKey: NACOS_AUTH_IDENTITY_VALUE
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: NACOS_AUTH_IDENTITY_VALUE
{{- end }}
