spark-operator:
  fullnameOverride: spark-operator

  controller:
    replicas: 1
    logLevel: info
    serviceAccount:
      create: true
      name: spark-operator
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

  webhook:
    enable: true
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi

  spark:
    jobNamespaces:
      - spark-jobs
      - flytesnacks-development
    serviceAccount:
      create: false
      name: spark
    rbac:
      create: true
    metrics:
      enable: true
