temporal:
  fullnameOverride: temporal

  server:
    replicaCount: 1
    metrics:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    config:
      logLevel: "info"
      persistence:
        defaultStore: default
        visibilityStore: visibility
        numHistoryShards: 128
        datastores:
          default:
            sql:
              createDatabase: false
              manageSchema: true
              pluginName: postgres12_pgx
              driverName: postgres12_pgx
              databaseName: temporal
              connectAddr: ai-video-temporal-dev.c8l6oosuk0q6.us-east-1.rds.amazonaws.com:5432
              connectProtocol: tcp
              user: temporal
              existingSecret: temporal-db
              secretKey: password
              maxConns: 20
              maxIdleConns: 20
              maxConnLifetime: 1h
          visibility:
            sql:
              createDatabase: false
              manageSchema: true
              pluginName: postgres12_pgx
              driverName: postgres12_pgx
              databaseName: temporal_visibility
              connectAddr: ai-video-temporal-dev.c8l6oosuk0q6.us-east-1.rds.amazonaws.com:5432
              connectProtocol: tcp
              user: temporal
              existingSecret: temporal-db
              secretKey: password
              maxConns: 10
              maxIdleConns: 10
              maxConnLifetime: 1h
      namespaces:
        create: true
        namespace:
          - name: default
            retention: 3d

    frontend:
      service:
        type: ClusterIP
        port: 7233

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

  admintools:
    enabled: true

  web:
    enabled: true
    service:
      type: ClusterIP
      port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  schema:
    useHelmHooks: false
    backoffLimit: 20
