{{- if .Values.kong.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ziyuanqishuo-frontend.name" . }}
  labels:
    {{- include "ziyuanqishuo-frontend.labels" . | nindent 4 }}
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: {{ .Values.kong.ingress.className }}
  rules:
    - http:
        paths:
          - path: {{ .Values.kong.ingress.path }}
            pathType: {{ .Values.kong.ingress.pathType }}
            backend:
              service:
                name: {{ include "ziyuanqishuo-frontend.name" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
