apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.components.web.name }}
  labels:
    {{- include "hello-springboot.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.components.web.replicaCount }}
  strategy:
    canary:
      steps:
        - setWeight: {{ .Values.rollout.canaryWeight }}
        - pause:
            duration: {{ .Values.rollout.pauseDuration }}
  selector:
    matchLabels:
      {{- include "hello-springboot.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "hello-springboot.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: {{ include "hello-springboot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: hello-web
          image: "{{ .Values.components.web.image.repository }}:{{ .Values.components.web.image.tag }}"
          imagePullPolicy: {{ .Values.components.web.image.pullPolicy }}
          env:
            - name: SERVICE_NAME
              value: {{ .Values.components.web.name | quote }}
            - name: APP_ENV
              value: "dev"
            {{- range $name, $value := .Values.components.web.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.components.web.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.components.web.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
