apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.components.grpc.name }}
  labels:
    {{- include "hello-springboot.labels" . | nindent 4 }}
    app.kubernetes.io/component: grpc
spec:
  replicas: {{ .Values.components.grpc.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello-springboot.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grpc
  template:
    metadata:
      labels:
        {{- include "hello-springboot.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grpc
    spec:
      serviceAccountName: {{ include "hello-springboot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: hello-grpc
          image: "{{ .Values.components.grpc.image.repository }}:{{ .Values.components.grpc.image.tag }}"
          imagePullPolicy: {{ .Values.components.grpc.image.pullPolicy }}
          env:
            - name: SERVICE_NAME
              value: {{ .Values.components.grpc.name | quote }}
            - name: APP_ENV
              value: "dev"
          ports:
            - name: http
              containerPort: {{ .Values.components.grpc.service.httpPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.components.grpc.service.grpcPort }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 10
            periodSeconds: 5
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.components.grpc.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
