apiVersion: apps/v1
kind: Deployment
metadata:
  name: ziyuanqishuo-db-public-tunnel
  labels:
    app.kubernetes.io/name: ziyuanqishuo-db-public-tunnel
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ziyuanqishuo-db-public-tunnel
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ziyuanqishuo-db-public-tunnel
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: socat
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "tcp-listen:{{ .Values.tunnel.listenPort }},fork,reuseaddr"
            - "tcp-connect:{{ .Values.tunnel.targetHost }}:{{ .Values.tunnel.targetPort }}"
          ports:
            - name: postgres
              containerPort: {{ .Values.tunnel.listenPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
