apiVersion: v1
kind: Service
metadata:
  name: ziyuanqishuo-db-public-tunnel
  labels:
    app.kubernetes.io/name: ziyuanqishuo-db-public-tunnel
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    app.kubernetes.io/name: ziyuanqishuo-db-public-tunnel
    app.kubernetes.io/instance: {{ .Release.Name }}
